### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by zLunarKnight** [Crazy-Crew/CrazyEnvoys#107]
### Server Version

1.8.8

### Server Platform

Spigot

### Describe the bug

I get this message when I open the server

ava.lang.NoClassDefFoundError: me/clip/placeholderapi/external/EZPlaceholderHook
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_362]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_362]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_362]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_362]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_362]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_362]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_362]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_362]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_362]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_362]
        at me.BadBones69.envoy.Main.onEnable(Main.java:51) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.external.EZPlaceholderHook
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_362]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_362]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_362]
        ... 27 more

### Steps to reproduce

see error

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
The only thing you can do is update or use an older version of PlaceholderAPI for 1.8.8 as we no longer support it.

![image](https://github.com/Crazy-Crew/CrazyEnvoys/assets/52214219/82971882-dc29-4d9d-adcf-f95297bc13a8)
